# Generated by Django 4.2.3 on 2023-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='length',
            field=models.DateField(null=True),
        ),
    ]
