# Generated by Django 4.2.3 on 2023-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_tracker', '0002_alter_period_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
