# Generated by Django 4.2.3 on 2023-07-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_tracker', '0003_alter_period_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='length',
        ),
    ]
